# Enable colors and and change prompt
autoload -U colors && colors
PS1="%B%{$fg[red]%}%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[white]%}%~ %{$fg[red]%}%{$reset_color%}$%b "

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

# Vim mode options
bindkey -v
bindkey '^R' history-incremental-search-backward
export KEYTIMEOUT=1 # Recomended
# Fix bug when switching modes
bindkey "^?" backward-delete-char

# Completion
autoload -Uz compinit
# select with menu
zstyle ':completion:*' menu select
# Case -insensitive completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*' # needed for idden files to work
zmodload zsh/complist # show command options
compinit
_comp_options+=(globdots) # for hidden files

# Do ls right after a cd(https://stackoverflow.com/questions/3964068/zsh-automatically-run-ls-after-every-cd)
function chpwd() {
    emulate -L zsh
    ls -G
}

export QSYS_ROOTDIR="/home/pablo/.cache/yay/quartus-free/pkg/quartus-free/opt/altera/19.1/quartus/sopc_builder/bin"

alias ls='ls -G'
alias v='nvim'
alias c='calcurse -D ~/Dropbox/calendar'
alias ran='ranger'
alias python='python3.10'
alias pip='pip3.10'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH=$PATH:/usr/local/bin/gfortran
